name: Build and run the samples
on:
  workflow_dispatch:
  pull_request:
  push:
    branches: ['main']
jobs:
  run-samples:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: pnpm/action-setup@v2
        with:
          version: 7
      - name: 'setup node with cache'
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'pnpm'
      - run: pnpm install
      - name: 'run the samples'
        run: |
          pnpm run build
          pnpm run rotation
          pnpm run reissuance
          pnpm run social
